[package]
name = "ml-runtime-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ml-runtime"
path = "src/main.rs"

[dependencies]
clap.workspace = true
ml-runtime = { path = "../runtime" }
ml-runtime-coreml-backend = { path = "../../backends/coreml" }
ml-runtime-cpu-backend = { path = "../../backends/cpu" }
ml-runtime-cuda-backend = { path = "../../backends/cuda" }
ml-runtime-http-provider = { path = "../../providers/http" }
ml-runtime-local-provider = { path = "../../providers/local" }
ml-runtime-model = { path = "../model" }
ml-runtime-onnx-backend = { path = "../../backends/onnx" }
ml-runtime-server-provider = { path = "../../providers/server" }
ml-runtime-webgpu-backend = { path = "../../backends/webgpu" }
serde_json.workspace = true
futures-util.workspace = true
tokio.workspace = true
