[package]
name = "ml-runtime-onnx-backend"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
futures-util.workspace = true
ml-runtime-common = { path = "../../crates/common" }
ml-runtime-inference = { path = "../../crates/inference" }
ml-runtime-backend = { path = "../../crates/backend" }
ml-runtime-model = { path = "../../crates/model" }
serde.workspace = true
