[package]
name = "ml-runtime-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Wire protocol types for rust-ml-runtime providers"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/ml-runtime-protocol"

[dependencies]
ml-runtime-inference = { version = "0.1.0", path = "../inference" }
ml-runtime-model = { version = "0.1.0", path = "../model" }
serde.workspace = true
